set(PLUGIN___MODULE_UPPER_NAME___NAME HobbyPlugin___MODULE_NAME__)
set(PLUGIN___MODULE_UPPER_NAME___INC_DIR ${CMAKE_CURRENT_LIST_DIR}/Inc)

# プロジェクトに登録するファイル群
# ここに全て記載する
set(PLUGIN___MODULE_UPPER_NAME___TARGET_COMMON_FILES
    .editorconfig
    LICENSE.txt
    README.md
)

set(PLUGIN___MODULE_UPPER_NAME___TARGET_INC_FILES
    Inc/__MODULE_NAME__Module.h
)

set(PLUGIN___MODULE_UPPER_NAME___TARGET_SRC_FILES
    Src/__MODULE_NAME__Module.cpp
)
